words = [
    "Mssp",
    "acls",
    "apikey",
    "autoclass",
    "autoexception",
    "badgatewayerror",
    "badrequesterror",
    "boxify",
    "bymonthday",
    "byweekday",
    "chpasswd",
    "cidr",
    "conv",
    "destringify",
    "devportal",
    "expectationfailederror",
    "forbiddenerror",
    "fulltext",
    "gatewaytimeouterror",
    "httpbin",
    "invalidmethoderror",
    "ips",
    "ipv",
    "lastlogin",
    "lce",
    "lengthrequirederror",
    "lobj",
    "maptable",
    "mdm",
    "methodnotimplimentederror",
    "misdirectrequesterror",
    "monkeypatch",
    "netbios",
    "networkauthrequirederror",
    "nolongerexistserror",
    "notacceptableerror",
    "notextendederror",
    "notfounderror",
    "opsys",
    "otype",
    "pathing",
    "payloadtoolargeerror",
    "pprint",
    "preconditionfailederror",
    "preconditionrequirederror",
    "proxyauthenticationerror",
    "rangenotsatisfiableerror",
    "recasted",
    "requestconflicterror",
    "requestheaderfieldstoolargeerror",
    "requesttimeouterror",
    "restfly",
    "rkeys",
    "rrules",
    "rval",
    "servererror",
    "serviceunavailableerror",
    "sms",
    "softcheck",
    "softchecks",
    "teapotresponseerror",
    "timedelta",
    "tio",
    "tooearlyerror",
    "toomanyrequests",
    "unauthorizederror",
    "unavailableforlegalreasonserror",
    "unexpectedvalue",
    "unsupportedmediatypeerror",
    "upgraderequirederror",
    "uritoolongerror",
    "urlparse",
    "utcnow",
]
