filters = {
    'assets': {
        'id': {'operators': ['equals', 'like', 'in', 'notIn']},
        'name': {'operators': ['equals', 'like', 'in', 'notIn']},
        'first_seen': {'name': 'firstSeen', 'operators': ['equals', 'like', 'in', 'less', 'greater', 'notIn']},
        'last_seen': {'name': 'lastSeen', 'operators': ['equals', 'like', 'in', 'less', 'greater', 'notIn']},
        'addresses': {'operators': ['contains', 'like', 'notIn']},
        'direct_addresses': {'name': 'directAddresses', 'operators': ['contains', 'like', 'notIn']},
        'type': {'operators': ['equals', 'like', 'in', 'notIn']},
        'purdue_level': {'name': 'purdueLevel', 'operators': ['equals', 'like', 'in', 'notIn']},
        'vendor': {'operators': ['equals', 'like', 'in', 'notIn']},
        'run_status': {'name': 'runStatus', 'operators': ['equals', 'like', 'in', 'notIn']},
        'runStatusTime': {'operators': ['equals', 'like', 'in', 'less', 'greater', 'notIn']},
        'location': {'operators': ['equals', 'like', 'in', 'notIn']},
        'description': {'operators': ['equals', 'like', 'in', 'notIn']},
        'os': {'operators': ['equals', 'like', 'in', 'notIn']},
        'family': {'operators': ['equals', 'like', 'in', 'notIn']},
        'modelName': {'operators': ['equals', 'like', 'in', 'notIn']},
        'firmware': {'operators': ['equals', 'like', 'in', 'notIn']},
        'slot': {'operators': ['equals', 'like', 'in', 'less', 'greater', 'notIn']},
        'backplane': {'operators': ['equals', 'like', 'in', 'notIn']},
        'risk': {'operators': ['equals', 'like', 'in', 'less', 'greater', 'notIn']},
        'criticality': {'operators': ['equals', 'like', 'in', 'less', 'greater', 'notIn']},
        'site': {'operators': ['equals', 'like', 'in', 'notIn']},
        'hidden': {'operators': ['equals', 'like', 'in', 'notIn']},
        'customField1': {'operators': ['equals', 'like', 'in', 'notIn']},
        'customField2': {'operators': ['equals', 'like', 'in', 'notIn']},
        'customField3': {'operators': ['equals', 'like', 'in', 'notIn']},
        'customField4': {'operators': ['equals', 'like', 'in', 'notIn']},
        'customField5': {'operators': ['equals', 'like', 'in', 'notIn']},
        'customField6': {'operators': ['equals', 'like', 'in', 'notIn']},
        'customField7': {'operators': ['equals', 'like', 'in', 'notIn']},
        'customField8': {'operators': ['equals', 'like', 'in', 'notIn']},
        'customField9': {'operators': ['equals', 'like', 'in', 'notIn']},
        'customField10': {'operators': ['equals', 'like', 'in', 'notIn']},
    }
}