# coding: utf-8

"""
    Tenable.ad - Client API

    API to interact with Tenable.ad   

    OpenAPI spec version: production
    

"""

import pprint

import six


class ApiattacksVector(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'template': 'str',
        'attributes': 'list[ApiattacksVectorAttributes]'
    }

    attribute_map = {
        'template': 'template',
        'attributes': 'attributes'
    }

    def __init__(self, template=None, attributes=None):
        """ApiattacksVector - a model defined in Swagger"""
        self._template = None
        self._attributes = None
        self.discriminator = None
        if template is not None:
            self.template = template
        if attributes is not None:
            self.attributes = attributes

    @property
    def template(self):
        """Gets the template of this ApiattacksVector.   


        :return: The template of this ApiattacksVector.   
        :rtype: str
        """
        return self._template

    @template.setter
    def template(self, template):
        """Sets the template of this ApiattacksVector.


        :param template: The template of this ApiattacksVector.   
        :type: str
        """

        self._template = template

    @property
    def attributes(self):
        """Gets the attributes of this ApiattacksVector.   


        :return: The attributes of this ApiattacksVector.   
        :rtype: list[ApiattacksVectorAttributes]
        """
        return self._attributes

    @attributes.setter
    def attributes(self, attributes):
        """Sets the attributes of this ApiattacksVector.


        :param attributes: The attributes of this ApiattacksVector.   
        :type: list[ApiattacksVectorAttributes]
        """

        self._attributes = attributes

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ApiattacksVector, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ApiattacksVector):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
