# coding: utf-8

"""
    Tenable.ad - Client API

    API to interact with Tenable.ad   

    OpenAPI spec version: production
    

"""

import pprint
import re

import six

class ApialertsioaAttackType(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'name': 'str',
        'criticity': 'str'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'criticity': 'criticity'
    }

    def __init__(self, id=None, name=None, criticity=None):   
        """ApialertsioaAttackType - a model defined in Swagger"""   
        self._id = None
        self._name = None
        self._criticity = None
        self.discriminator = None
        self.id = id
        self.name = name
        self.criticity = criticity

    @property
    def id(self):
        """Gets the id of this ApialertsioaAttackType.   


        :return: The id of this ApialertsioaAttackType.   
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ApialertsioaAttackType.


        :param id: The id of this ApialertsioaAttackType.   
        :type: int
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")   

        self._id = id

    @property
    def name(self):
        """Gets the name of this ApialertsioaAttackType.   


        :return: The name of this ApialertsioaAttackType.   
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ApialertsioaAttackType.


        :param name: The name of this ApialertsioaAttackType.   
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")   

        self._name = name

    @property
    def criticity(self):
        """Gets the criticity of this ApialertsioaAttackType.   


        :return: The criticity of this ApialertsioaAttackType.   
        :rtype: str
        """
        return self._criticity

    @criticity.setter
    def criticity(self, criticity):
        """Sets the criticity of this ApialertsioaAttackType.


        :param criticity: The criticity of this ApialertsioaAttackType.   
        :type: str
        """
        if criticity is None:
            raise ValueError("Invalid value for `criticity`, must not be `None`")   
        allowed_values = ["critical", "high", "medium", "low"]   
        if criticity not in allowed_values:
            raise ValueError(
                "Invalid value for `criticity` ({0}), must be one of {1}"   
                .format(criticity, allowed_values)
            )

        self._criticity = criticity

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ApialertsioaAttackType, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ApialertsioaAttackType):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
