# coding: utf-8

"""
    Tenable.ad - Client API

    API to interact with Tenable.ad   

    OpenAPI spec version: production
    

"""

import pprint
import re   

import six

class ApiprofilesprofileIdcheckerscheckerIdadobjectssearchObjectAttributes(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'value': 'str',
        'value_type': 'str'
    }

    attribute_map = {
        'name': 'name',
        'value': 'value',
        'value_type': 'valueType'
    }

    def __init__(self, name=None, value=None, value_type=None):   
        """ApiprofilesprofileIdcheckerscheckerIdadobjectssearchObjectAttributes - a model defined in Swagger"""   
        self._name = None
        self._value = None
        self._value_type = None
        self.discriminator = None
        self.name = name
        self.value = value
        self.value_type = value_type

    @property
    def name(self):
        """Gets the name of this ApiprofilesprofileIdcheckerscheckerIdadobjectssearchObjectAttributes.   


        :return: The name of this ApiprofilesprofileIdcheckerscheckerIdadobjectssearchObjectAttributes.   
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ApiprofilesprofileIdcheckerscheckerIdadobjectssearchObjectAttributes.


        :param name: The name of this ApiprofilesprofileIdcheckerscheckerIdadobjectssearchObjectAttributes.   
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")   

        self._name = name

    @property
    def value(self):
        """Gets the value of this ApiprofilesprofileIdcheckerscheckerIdadobjectssearchObjectAttributes.   


        :return: The value of this ApiprofilesprofileIdcheckerscheckerIdadobjectssearchObjectAttributes.   
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this ApiprofilesprofileIdcheckerscheckerIdadobjectssearchObjectAttributes.


        :param value: The value of this ApiprofilesprofileIdcheckerscheckerIdadobjectssearchObjectAttributes.   
        :type: str
        """
        if value is None:
            raise ValueError("Invalid value for `value`, must not be `None`")   

        self._value = value

    @property
    def value_type(self):
        """Gets the value_type of this ApiprofilesprofileIdcheckerscheckerIdadobjectssearchObjectAttributes.   


        :return: The value_type of this ApiprofilesprofileIdcheckerscheckerIdadobjectssearchObjectAttributes.   
        :rtype: str
        """
        return self._value_type

    @value_type.setter
    def value_type(self, value_type):
        """Sets the value_type of this ApiprofilesprofileIdcheckerscheckerIdadobjectssearchObjectAttributes.


        :param value_type: The value_type of this ApiprofilesprofileIdcheckerscheckerIdadobjectssearchObjectAttributes.   
        :type: str
        """
        if value_type is None:
            raise ValueError("Invalid value for `value_type`, must not be `None`")   
        allowed_values = ["boolean", "string", "integer", "date", "object", "array/boolean", "array/string", "array/integer", "array/date", "array/object"]   
        if value_type not in allowed_values:
            raise ValueError(
                "Invalid value for `value_type` ({0}), must be one of {1}"   
                .format(value_type, allowed_values)
            )

        self._value_type = value_type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ApiprofilesprofileIdcheckerscheckerIdadobjectssearchObjectAttributes, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ApiprofilesprofileIdcheckerscheckerIdadobjectssearchObjectAttributes):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
