# coding: utf-8

"""
    Tenable.ad - Client API

    API to interact with Tenable.ad

    OpenAPI spec version: production
    

"""

import pprint

import six


class ApisamlconfigurationAllowedGroups(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'default_profile_id': 'int',
        'default_role_ids': 'list[int]'
    }

    attribute_map = {
        'name': 'name',
        'default_profile_id': 'defaultProfileId',
        'default_role_ids': 'defaultRoleIds'
    }

    def __init__(self, name=None, default_profile_id=None, default_role_ids=None):
        """ApisamlconfigurationAllowedGroups - a model defined in Swagger"""
        self._name = None
        self._default_profile_id = None
        self._default_role_ids = None
        self.discriminator = None
        self.name = name
        self.default_profile_id = default_profile_id
        self.default_role_ids = default_role_ids

    @property
    def name(self):
        """Gets the name of this ApisamlconfigurationAllowedGroups.


        :return: The name of this ApisamlconfigurationAllowedGroups.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ApisamlconfigurationAllowedGroups.


        :param name: The name of this ApisamlconfigurationAllowedGroups.
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")

        self._name = name

    @property
    def default_profile_id(self):
        """Gets the default_profile_id of this ApisamlconfigurationAllowedGroups.


        :return: The default_profile_id of this ApisamlconfigurationAllowedGroups.
        :rtype: int
        """
        return self._default_profile_id

    @default_profile_id.setter
    def default_profile_id(self, default_profile_id):
        """Sets the default_profile_id of this ApisamlconfigurationAllowedGroups.


        :param default_profile_id: The default_profile_id of this ApisamlconfigurationAllowedGroups.
        :type: int
        """
        if default_profile_id is None:
            raise ValueError("Invalid value for `default_profile_id`, must not be `None`")

        self._default_profile_id = default_profile_id

    @property
    def default_role_ids(self):
        """Gets the default_role_ids of this ApisamlconfigurationAllowedGroups.


        :return: The default_role_ids of this ApisamlconfigurationAllowedGroups.
        :rtype: list[int]
        """
        return self._default_role_ids

    @default_role_ids.setter
    def default_role_ids(self, default_role_ids):
        """Sets the default_role_ids of this ApisamlconfigurationAllowedGroups.


        :param default_role_ids: The default_role_ids of this ApisamlconfigurationAllowedGroups.
        :type: list[int]
        """
        if default_role_ids is None:
            raise ValueError("Invalid value for `default_role_ids`, must not be `None`")

        self._default_role_ids = default_role_ids

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ApisamlconfigurationAllowedGroups, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ApisamlconfigurationAllowedGroups):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
