# coding: utf-8

"""
    Tenable.ad - Client API

    API to interact with Tenable.ad   

    OpenAPI spec version: production
    

"""

import pprint
import re   

import six

class InlineResponse20030(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'language': 'str',
        'preferred_profile_id': 'int'
    }

    attribute_map = {
        'language': 'language',
        'preferred_profile_id': 'preferredProfileId'
    }

    def __init__(self, language=None, preferred_profile_id=None):   
        """InlineResponse20030 - a model defined in Swagger"""   
        self._language = None
        self._preferred_profile_id = None
        self.discriminator = None
        self.language = language
        self.preferred_profile_id = preferred_profile_id

    @property
    def language(self):
        """Gets the language of this InlineResponse20030.   


        :return: The language of this InlineResponse20030.   
        :rtype: str
        """
        return self._language

    @language.setter
    def language(self, language):
        """Sets the language of this InlineResponse20030.


        :param language: The language of this InlineResponse20030.   
        :type: str
        """
        if language is None:
            raise ValueError("Invalid value for `language`, must not be `None`")   

        self._language = language

    @property
    def preferred_profile_id(self):
        """Gets the preferred_profile_id of this InlineResponse20030.   


        :return: The preferred_profile_id of this InlineResponse20030.   
        :rtype: int
        """
        return self._preferred_profile_id

    @preferred_profile_id.setter
    def preferred_profile_id(self, preferred_profile_id):
        """Sets the preferred_profile_id of this InlineResponse20030.


        :param preferred_profile_id: The preferred_profile_id of this InlineResponse20030.   
        :type: int
        """
        if preferred_profile_id is None:
            raise ValueError("Invalid value for `preferred_profile_id`, must not be `None`")   

        self._preferred_profile_id = preferred_profile_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse20030, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse20030):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
