# coding: utf-8

"""
    Tenable.ad - Client API

    API to interact with Tenable.ad

    OpenAPI spec version: production
    

"""

import pprint

import six


class ApiinfrastructuresinfrastructureIddirectoriesdirectoryIddeviancesDescription(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'template': 'str',
        'replacements': 'list[ApiinfrastructuresinfrastructureIddirectoriesdirectoryIddeviancesDescriptionReplacements]'
    }

    attribute_map = {
        'template': 'template',
        'replacements': 'replacements'
    }

    def __init__(self, template=None, replacements=None):
        """ApiinfrastructuresinfrastructureIddirectoriesdirectoryIddeviancesDescription - a model defined in Swagger"""
        self._template = None
        self._replacements = None
        self.discriminator = None
        self.template = template
        self.replacements = replacements

    @property
    def template(self):
        """Gets the template of this ApiinfrastructuresinfrastructureIddirectoriesdirectoryIddeviancesDescription.


        :return: The template of this ApiinfrastructuresinfrastructureIddirectoriesdirectoryIddeviancesDescription.
        :rtype: str
        """
        return self._template

    @template.setter
    def template(self, template):
        """Sets the template of this ApiinfrastructuresinfrastructureIddirectoriesdirectoryIddeviancesDescription.


        :param template: The template of this ApiinfrastructuresinfrastructureIddirectoriesdirectoryIddeviancesDescription.
        :type: str
        """
        if template is None:
            raise ValueError("Invalid value for `template`, must not be `None`")

        self._template = template

    @property
    def replacements(self):
        """Gets the replacements of this ApiinfrastructuresinfrastructureIddirectoriesdirectoryIddeviancesDescription.


        :return: The replacements of this ApiinfrastructuresinfrastructureIddirectoriesdirectoryIddeviancesDescription.
        :rtype: list[ApiinfrastructuresinfrastructureIddirectoriesdirectoryIddeviancesDescriptionReplacements]
        """
        return self._replacements

    @replacements.setter
    def replacements(self, replacements):
        """Sets the replacements of this ApiinfrastructuresinfrastructureIddirectoriesdirectoryIddeviancesDescription.


        :param replacements: The replacements of this ApiinfrastructuresinfrastructureIddirectoriesdirectoryIddeviancesDescription.
        :type: list[ApiinfrastructuresinfrastructureIddirectoriesdirectoryIddeviancesDescriptionReplacements]
        """
        if replacements is None:
            raise ValueError("Invalid value for `replacements`, must not be `None`")

        self._replacements = replacements

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ApiinfrastructuresinfrastructureIddirectoriesdirectoryIddeviancesDescription, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ApiinfrastructuresinfrastructureIddirectoriesdirectoryIddeviancesDescription):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
