# coding: utf-8

"""
    Tenable.ad - Client API

    API to interact with Tenable.ad

    OpenAPI spec version: production
    

"""

import pprint

import six


class DirectoriesIdBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'ip': 'str',
        'type': 'str',
        'ldap_port': 'int',
        'global_catalog_port': 'int',
        'smb_port': 'int',
        'dns': 'str'
    }

    attribute_map = {
        'name': 'name',
        'ip': 'ip',
        'type': 'type',
        'ldap_port': 'ldapPort',
        'global_catalog_port': 'globalCatalogPort',
        'smb_port': 'smbPort',
        'dns': 'dns'
    }

    def __init__(self, name=None, ip=None, type=None, ldap_port=None, global_catalog_port=None, smb_port=None,
                 dns=None):
        """DirectoriesIdBody - a model defined in Swagger"""
        self._name = None
        self._ip = None
        self._type = None
        self._ldap_port = None
        self._global_catalog_port = None
        self._smb_port = None
        self._dns = None
        self.discriminator = None
        if name is not None:
            self.name = name
        if ip is not None:
            self.ip = ip
        if type is not None:
            self.type = type
        if ldap_port is not None:
            self.ldap_port = ldap_port
        if global_catalog_port is not None:
            self.global_catalog_port = global_catalog_port
        if smb_port is not None:
            self.smb_port = smb_port
        if dns is not None:
            self.dns = dns

    @property
    def name(self):
        """Gets the name of this DirectoriesIdBody.


        :return: The name of this DirectoriesIdBody.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this DirectoriesIdBody.


        :param name: The name of this DirectoriesIdBody.
        :type: str
        """

        self._name = name

    @property
    def ip(self):
        """Gets the ip of this DirectoriesIdBody.


        :return: The ip of this DirectoriesIdBody.
        :rtype: str
        """
        return self._ip

    @ip.setter
    def ip(self, ip):
        """Sets the ip of this DirectoriesIdBody.


        :param ip: The ip of this DirectoriesIdBody.
        :type: str
        """

        self._ip = ip

    @property
    def type(self):
        """Gets the type of this DirectoriesIdBody.


        :return: The type of this DirectoriesIdBody.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this DirectoriesIdBody.


        :param type: The type of this DirectoriesIdBody.
        :type: str
        """

        self._type = type

    @property
    def ldap_port(self):
        """Gets the ldap_port of this DirectoriesIdBody.


        :return: The ldap_port of this DirectoriesIdBody.
        :rtype: int
        """
        return self._ldap_port

    @ldap_port.setter
    def ldap_port(self, ldap_port):
        """Sets the ldap_port of this DirectoriesIdBody.


        :param ldap_port: The ldap_port of this DirectoriesIdBody.
        :type: int
        """

        self._ldap_port = ldap_port

    @property
    def global_catalog_port(self):
        """Gets the global_catalog_port of this DirectoriesIdBody.


        :return: The global_catalog_port of this DirectoriesIdBody.
        :rtype: int
        """
        return self._global_catalog_port

    @global_catalog_port.setter
    def global_catalog_port(self, global_catalog_port):
        """Sets the global_catalog_port of this DirectoriesIdBody.


        :param global_catalog_port: The global_catalog_port of this DirectoriesIdBody.
        :type: int
        """

        self._global_catalog_port = global_catalog_port

    @property
    def smb_port(self):
        """Gets the smb_port of this DirectoriesIdBody.


        :return: The smb_port of this DirectoriesIdBody.
        :rtype: int
        """
        return self._smb_port

    @smb_port.setter
    def smb_port(self, smb_port):
        """Sets the smb_port of this DirectoriesIdBody.


        :param smb_port: The smb_port of this DirectoriesIdBody.
        :type: int
        """

        self._smb_port = smb_port

    @property
    def dns(self):
        """Gets the dns of this DirectoriesIdBody.


        :return: The dns of this DirectoriesIdBody.
        :rtype: str
        """
        return self._dns

    @dns.setter
    def dns(self, dns):
        """Sets the dns of this DirectoriesIdBody.


        :param dns: The dns of this DirectoriesIdBody.
        :type: str
        """

        self._dns = dns

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DirectoriesIdBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DirectoriesIdBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
