# coding: utf-8

"""
    Tenable.ad - Client API

    API to interact with Tenable.ad   

    OpenAPI spec version: production
    

"""

import pprint
import re

import six

class InfrastructuresIdBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'login': 'str',
        'password': 'str'
    }

    attribute_map = {
        'name': 'name',
        'login': 'login',
        'password': 'password'
    }

    def __init__(self, name=None, login=None, password=None):   
        """InfrastructuresIdBody - a model defined in Swagger"""   
        self._name = None
        self._login = None
        self._password = None
        self.discriminator = None
        if name is not None:
            self.name = name
        if login is not None:
            self.login = login
        if password is not None:
            self.password = password

    @property
    def name(self):
        """Gets the name of this InfrastructuresIdBody.   


        :return: The name of this InfrastructuresIdBody.   
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this InfrastructuresIdBody.


        :param name: The name of this InfrastructuresIdBody.   
        :type: str
        """

        self._name = name

    @property
    def login(self):
        """Gets the login of this InfrastructuresIdBody.   


        :return: The login of this InfrastructuresIdBody.   
        :rtype: str
        """
        return self._login

    @login.setter
    def login(self, login):
        """Sets the login of this InfrastructuresIdBody.


        :param login: The login of this InfrastructuresIdBody.   
        :type: str
        """

        self._login = login

    @property
    def password(self):
        """Gets the password of this InfrastructuresIdBody.   


        :return: The password of this InfrastructuresIdBody.   
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password):
        """Sets the password of this InfrastructuresIdBody.


        :param password: The password of this InfrastructuresIdBody.   
        :type: str
        """

        self._password = password

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InfrastructuresIdBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InfrastructuresIdBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
