# coding: utf-8

"""
    Tenable.ad - Client API

    API to interact with Tenable.ad

    OpenAPI spec version: production
    

"""

import pprint

import six


class InlineResponse2009(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'float',
        'directory_id': 'float',
        'attack_type_id': 'float',
        'dc': 'str',
        '_date': 'datetime',
        'vector': 'ApiattacksVector',
        'source': 'ApiattacksSource',
        'target': 'ApiattacksSource'
    }

    attribute_map = {
        'id': 'id',
        'directory_id': 'directoryId',
        'attack_type_id': 'attackTypeId',
        'dc': 'dc',
        '_date': 'date',
        'vector': 'vector',
        'source': 'source',
        'target': 'target'
    }

    def __init__(self, id=None, directory_id=None, attack_type_id=None, dc=None, _date=None, vector=None, source=None,
                 target=None):
        """InlineResponse2009 - a model defined in Swagger"""
        self._id = None
        self._directory_id = None
        self._attack_type_id = None
        self._dc = None
        self.__date = None
        self._vector = None
        self._source = None
        self._target = None
        self.discriminator = None
        self.id = id
        self.directory_id = directory_id
        self.attack_type_id = attack_type_id
        self.dc = dc
        self._date = _date
        self.vector = vector
        self.source = source
        self.target = target

    @property
    def id(self):
        """Gets the id of this InlineResponse2009.


        :return: The id of this InlineResponse2009.
        :rtype: float
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this InlineResponse2009.


        :param id: The id of this InlineResponse2009.
        :type: float
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")

        self._id = id

    @property
    def directory_id(self):
        """Gets the directory_id of this InlineResponse2009.


        :return: The directory_id of this InlineResponse2009.
        :rtype: float
        """
        return self._directory_id

    @directory_id.setter
    def directory_id(self, directory_id):
        """Sets the directory_id of this InlineResponse2009.


        :param directory_id: The directory_id of this InlineResponse2009.
        :type: float
        """
        if directory_id is None:
            raise ValueError("Invalid value for `directory_id`, must not be `None`")

        self._directory_id = directory_id

    @property
    def attack_type_id(self):
        """Gets the attack_type_id of this InlineResponse2009.


        :return: The attack_type_id of this InlineResponse2009.
        :rtype: float
        """
        return self._attack_type_id

    @attack_type_id.setter
    def attack_type_id(self, attack_type_id):
        """Sets the attack_type_id of this InlineResponse2009.


        :param attack_type_id: The attack_type_id of this InlineResponse2009.
        :type: float
        """
        if attack_type_id is None:
            raise ValueError("Invalid value for `attack_type_id`, must not be `None`")

        self._attack_type_id = attack_type_id

    @property
    def dc(self):
        """Gets the dc of this InlineResponse2009.


        :return: The dc of this InlineResponse2009.
        :rtype: str
        """
        return self._dc

    @dc.setter
    def dc(self, dc):
        """Sets the dc of this InlineResponse2009.


        :param dc: The dc of this InlineResponse2009.
        :type: str
        """
        if dc is None:
            raise ValueError("Invalid value for `dc`, must not be `None`")

        self._dc = dc

    @property
    def _date(self):
        """Gets the _date of this InlineResponse2009.


        :return: The _date of this InlineResponse2009.
        :rtype: datetime
        """
        return self.__date

    @_date.setter
    def _date(self, _date):
        """Sets the _date of this InlineResponse2009.


        :param _date: The _date of this InlineResponse2009.
        :type: datetime
        """
        if _date is None:
            raise ValueError("Invalid value for `_date`, must not be `None`")

        self.__date = _date

    @property
    def vector(self):
        """Gets the vector of this InlineResponse2009.


        :return: The vector of this InlineResponse2009.
        :rtype: ApiattacksVector
        """
        return self._vector

    @vector.setter
    def vector(self, vector):
        """Sets the vector of this InlineResponse2009.


        :param vector: The vector of this InlineResponse2009.
        :type: ApiattacksVector
        """
        if vector is None:
            raise ValueError("Invalid value for `vector`, must not be `None`")

        self._vector = vector

    @property
    def source(self):
        """Gets the source of this InlineResponse2009.


        :return: The source of this InlineResponse2009.
        :rtype: ApiattacksSource
        """
        return self._source

    @source.setter
    def source(self, source):
        """Sets the source of this InlineResponse2009.


        :param source: The source of this InlineResponse2009.
        :type: ApiattacksSource
        """
        if source is None:
            raise ValueError("Invalid value for `source`, must not be `None`")

        self._source = source

    @property
    def target(self):
        """Gets the target of this InlineResponse2009.


        :return: The target of this InlineResponse2009.
        :rtype: ApiattacksSource
        """
        return self._target

    @target.setter
    def target(self, target):
        """Sets the target of this InlineResponse2009.


        :param target: The target of this InlineResponse2009.
        :type: ApiattacksSource
        """
        if target is None:
            raise ValueError("Invalid value for `target`, must not be `None`")

        self._target = target

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse2009, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse2009):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
