# coding: utf-8

"""
    Tenable.ad - Client API

    API to interact with Tenable.ad

    OpenAPI spec version: production
    

"""

import pprint
import re

import six

class SyslogsIdBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'ip': 'str',
        'port': 'int',
        'protocol': 'str',
        'tls': 'bool',
        'criticity_threshold': 'int',
        'description': 'str',
        'filter_expression': 'object',
        'input_type': 'str',
        'directories': 'list[int]',
        'checkers': 'list[int]',
        'profiles': 'list[int]',
        'attack_types': 'list[int]'
    }

    attribute_map = {
        'ip': 'ip',
        'port': 'port',
        'protocol': 'protocol',
        'tls': 'tls',
        'criticity_threshold': 'criticityThreshold',
        'description': 'description',
        'filter_expression': 'filterExpression',
        'input_type': 'inputType',
        'directories': 'directories',
        'checkers': 'checkers',
        'profiles': 'profiles',
        'attack_types': 'attackTypes'
    }

    def __init__(self, ip=None, port=None, protocol=None, tls=None, criticity_threshold=None, description=None, filter_expression=None, input_type=None, directories=None, checkers=None, profiles=None, attack_types=None):
        """SyslogsIdBody - a model defined in Swagger"""
        self._ip = None
        self._port = None
        self._protocol = None
        self._tls = None
        self._criticity_threshold = None
        self._description = None
        self._filter_expression = None
        self._input_type = None
        self._directories = None
        self._checkers = None
        self._profiles = None
        self._attack_types = None
        self.discriminator = None
        if ip is not None:
            self.ip = ip
        if port is not None:
            self.port = port
        if protocol is not None:
            self.protocol = protocol
        if tls is not None:
            self.tls = tls
        if criticity_threshold is not None:
            self.criticity_threshold = criticity_threshold
        if description is not None:
            self.description = description
        if filter_expression is not None:
            self.filter_expression = filter_expression
        if input_type is not None:
            self.input_type = input_type
        if directories is not None:
            self.directories = directories
        if checkers is not None:
            self.checkers = checkers
        if profiles is not None:
            self.profiles = profiles
        if attack_types is not None:
            self.attack_types = attack_types

    @property
    def ip(self):
        """Gets the ip of this SyslogsIdBody.


        :return: The ip of this SyslogsIdBody.
        :rtype: str
        """
        return self._ip

    @ip.setter
    def ip(self, ip):
        """Sets the ip of this SyslogsIdBody.


        :param ip: The ip of this SyslogsIdBody.
        :type: str
        """

        self._ip = ip

    @property
    def port(self):
        """Gets the port of this SyslogsIdBody.


        :return: The port of this SyslogsIdBody.
        :rtype: int
        """
        return self._port

    @port.setter
    def port(self, port):
        """Sets the port of this SyslogsIdBody.


        :param port: The port of this SyslogsIdBody.
        :type: int
        """

        self._port = port

    @property
    def protocol(self):
        """Gets the protocol of this SyslogsIdBody.


        :return: The protocol of this SyslogsIdBody.
        :rtype: str
        """
        return self._protocol

    @protocol.setter
    def protocol(self, protocol):
        """Sets the protocol of this SyslogsIdBody.


        :param protocol: The protocol of this SyslogsIdBody.
        :type: str
        """
        allowed_values = ["UDP", "TCP"]
        if protocol not in allowed_values:
            raise ValueError(
                "Invalid value for `protocol` ({0}), must be one of {1}"
                .format(protocol, allowed_values)
            )

        self._protocol = protocol

    @property
    def tls(self):
        """Gets the tls of this SyslogsIdBody.


        :return: The tls of this SyslogsIdBody.
        :rtype: bool
        """
        return self._tls

    @tls.setter
    def tls(self, tls):
        """Sets the tls of this SyslogsIdBody.


        :param tls: The tls of this SyslogsIdBody.
        :type: bool
        """

        self._tls = tls

    @property
    def criticity_threshold(self):
        """Gets the criticity_threshold of this SyslogsIdBody.


        :return: The criticity_threshold of this SyslogsIdBody.
        :rtype: int
        """
        return self._criticity_threshold

    @criticity_threshold.setter
    def criticity_threshold(self, criticity_threshold):
        """Sets the criticity_threshold of this SyslogsIdBody.


        :param criticity_threshold: The criticity_threshold of this SyslogsIdBody.
        :type: int
        """

        self._criticity_threshold = criticity_threshold

    @property
    def description(self):
        """Gets the description of this SyslogsIdBody.


        :return: The description of this SyslogsIdBody.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this SyslogsIdBody.


        :param description: The description of this SyslogsIdBody.
        :type: str
        """

        self._description = description

    @property
    def filter_expression(self):
        """Gets the filter_expression of this SyslogsIdBody.


        :return: The filter_expression of this SyslogsIdBody.
        :rtype: object
        """
        return self._filter_expression

    @filter_expression.setter
    def filter_expression(self, filter_expression):
        """Sets the filter_expression of this SyslogsIdBody.


        :param filter_expression: The filter_expression of this SyslogsIdBody.
        :type: object
        """

        self._filter_expression = filter_expression

    @property
    def input_type(self):
        """Gets the input_type of this SyslogsIdBody.


        :return: The input_type of this SyslogsIdBody.
        :rtype: str
        """
        return self._input_type

    @input_type.setter
    def input_type(self, input_type):
        """Sets the input_type of this SyslogsIdBody.


        :param input_type: The input_type of this SyslogsIdBody.
        :type: str
        """
        allowed_values = ["deviances", "adObjectChanges", "attacks"]
        if input_type not in allowed_values:
            raise ValueError(
                "Invalid value for `input_type` ({0}), must be one of {1}"
                .format(input_type, allowed_values)
            )

        self._input_type = input_type

    @property
    def directories(self):
        """Gets the directories of this SyslogsIdBody.


        :return: The directories of this SyslogsIdBody.
        :rtype: list[int]
        """
        return self._directories

    @directories.setter
    def directories(self, directories):
        """Sets the directories of this SyslogsIdBody.


        :param directories: The directories of this SyslogsIdBody.
        :type: list[int]
        """

        self._directories = directories

    @property
    def checkers(self):
        """Gets the checkers of this SyslogsIdBody.


        :return: The checkers of this SyslogsIdBody.
        :rtype: list[int]
        """
        return self._checkers

    @checkers.setter
    def checkers(self, checkers):
        """Sets the checkers of this SyslogsIdBody.


        :param checkers: The checkers of this SyslogsIdBody.
        :type: list[int]
        """

        self._checkers = checkers

    @property
    def profiles(self):
        """Gets the profiles of this SyslogsIdBody.


        :return: The profiles of this SyslogsIdBody.
        :rtype: list[int]
        """
        return self._profiles

    @profiles.setter
    def profiles(self, profiles):
        """Sets the profiles of this SyslogsIdBody.


        :param profiles: The profiles of this SyslogsIdBody.
        :type: list[int]
        """

        self._profiles = profiles

    @property
    def attack_types(self):
        """Gets the attack_types of this SyslogsIdBody.


        :return: The attack_types of this SyslogsIdBody.
        :rtype: list[int]
        """
        return self._attack_types

    @attack_types.setter
    def attack_types(self, attack_types):
        """Sets the attack_types of this SyslogsIdBody.


        :param attack_types: The attack_types of this SyslogsIdBody.
        :type: list[int]
        """

        self._attack_types = attack_types

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SyslogsIdBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SyslogsIdBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
