name: Security Testing Pipeline

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 0 * * *"

jobs:
  security_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: "3.12"
      - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b
      - uses: snyk/actions/setup@master
      - uses: extractions/setup-just@v4

      - name: OSS Security Audits
        run: just audit

      - name: Snyk Scan
        run: just snyk
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          SNYK_CFG_ORG: ${{ secrets.SNYK_CFG_ORG }}
