name: Testing Pipeline

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 0 * * *"

jobs:
  security_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - uses: astral-sh/setup-uv@v4

      - name: Run pip-audit
        run: |
          uv export --format requirements-txt | uv tool run pip-audit

      - name: Run Bandit code auditor
        run: uv tool run --with "bandit[toml,baseline,sarif]" bandit -c pyproject.toml -r . -ll
      
      - name: Export & Install requirements to run Snyk
        run: |
          uv pip compile pyproject.toml -o requirements.txt
          pip3 install -r requirements.txt

      - name: Snyk Scan
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor --command=python3 --skip-unresolved=true
